### ISSUE TITLE
doLeftOuterJoin mutates input queries

### ISSUE THREAD

**Issue by Leftbower** [ColdBox/cbox-cbcommons#2]
QueryHelper's function doLeftOuterJoin can modify the original, passed in queries. Fix by using duplicate() on lines 250 and 251 when assigning them to internal var qry1 and qry2.

**Comment by lmajano** [comment]
Thanks, will you be sending a pull request?

**Comment by Leftbower** [comment]
done... hope I did it correctly?!

**Comment by lmajano** [comment]
Awesomeness!!
